### ISSUE TITLE
Inverse will fail for a non-empty string

### ISSUE THREAD

**Issue by t1m-l** [yegor256/j5#5]
https://github.com/yegor256/j5inno/blob/master/src/Inverse.java

# Description

Looks like the for loop initialization is incorrect, as its body part `text.charAt(p)` would fail, since at the first iteration `p = text.length()` which will throw index out of bound exception.

# Suggestion

Usage of some standard utility function to reverse string would help.

**Comment by ratijas** [comment]
Using proper iterators will help even more. I doubt even standard utilities use something else beyond direct indexing.
